defmodule AshBaml.Examples.BamlClient.Types do
  @moduledoc """
  Mock BAML type definitions for the agentic assistant examples.

  In a real application, these would be generated by running:
    mix ash_baml.gen.types AshBaml.Examples.BamlClient

  These types correspond to BAML class definitions like:

      // In baml_src/types.baml
      class LookupOrder {
        order_id string
      }

      class CreateTicket {
        issue string
        priority string
        category string
      }

      // etc...
  """

  # ============================================================
  # Customer Support Agent Types
  # ============================================================

  defmodule LookupOrder do
    @moduledoc "Tool to look up an order"
    use Ash.TypedStruct

    typed_struct do
      field :order_id, :string
    end
  end

  defmodule CreateTicket do
    @moduledoc "Tool to create a support ticket"
    use Ash.TypedStruct

    typed_struct do
      field :issue, :string
      field :priority, :string
      field :category, :string
    end
  end

  defmodule EscalateToHuman do
    @moduledoc "Tool to escalate to a human agent"
    use Ash.TypedStruct

    typed_struct do
      field :reason, :string
      field :urgency, :string
    end
  end

  # ============================================================
  # Shopping Assistant Types
  # ============================================================

  defmodule SearchProducts do
    @moduledoc "Tool to search for products"
    use Ash.TypedStruct

    typed_struct do
      field :query, :string
      field :category, :string
      field :max_price, :decimal
    end
  end

  defmodule AddToCart do
    @moduledoc "Tool to add an item to the cart"
    use Ash.TypedStruct

    typed_struct do
      field :product_id, :string
      field :quantity, :integer
    end
  end

  defmodule RemoveFromCart do
    @moduledoc "Tool to remove an item from the cart"
    use Ash.TypedStruct

    typed_struct do
      field :product_id, :string
    end
  end

  defmodule Checkout do
    @moduledoc "Tool to proceed to checkout"
    use Ash.TypedStruct

    typed_struct do
      field :payment_method, :string
      field :shipping_address_id, :string
    end
  end
end
