defmodule Helpdesk.BamlClient do
  @moduledoc """
  BAML client for Helpdesk.BamlClient.

  Generated by ash_baml. This module provides the interface to BAML functions
  defined in baml_src/.

  To regenerate types after modifying BAML schemas:

      mix ash_baml.gen.types Helpdesk.BamlClient
  """

  use BamlElixir.Client,
    baml_src: "baml_src"

  def __baml_src_path__ do
    Path.join(File.cwd!(), "baml_src")
  end
end
