defmodule AshBaml.Test.AutoGeneratedTestResource do
  @moduledoc """
  Test resource that uses import_functions to auto-generate actions.

  Used to test the import_functions feature that automatically creates
  both regular and streaming actions from BAML functions.
  """

  use Ash.Resource,
    domain: AshBaml.Test.TestDomain,
    extensions: [AshBaml.Resource]

  baml do
    client(:test)
    import_functions([:TestFunction])
  end

  # Also define a manual action with the name tests expect
  actions do
    action :test_action_stream, AshBaml.Type.Stream do
      argument(:message, :string, allow_nil?: false)
      constraints(element_type: :map)
      run(call_baml_stream(:TestFunction))
    end
  end
end
