defmodule AshBaml.Test.AutoGeneratedTestResource do
  @moduledoc false
  # Test resource that uses import_functions to auto-generate actions

  use Ash.Resource,
    domain: AshBaml.Test.TestDomain,
    extensions: [AshBaml.Resource]

  baml do
    client_module(AshBaml.Test.BamlClient)
    import_functions([:TestFunction])
  end

  # Actions should be auto-generated:
  # - :test_function (regular)
  # - :test_function_stream (streaming)
end
