defmodule Mix.Tasks.AshBaml.Install do
  use Igniter.Mix.Task

  @example "mix ash_baml.install --module MyApp.BamlClient"

  @shortdoc "Generates a BAML client module and example BAML files"

  @moduledoc """
  #{@shortdoc}

  ## Example

  ```bash
  #{@example}
  ```

  ## Options

  * `--module` - Required. The module name for your BAML client (e.g., MyApp.BamlClient)
  * `--path` - Optional. Path to the baml_src directory. Defaults to "baml_src"
  """

  def info(_argv, _composing_task) do
    %Igniter.Mix.Task.Info{
      schema: [
        module: :string,
        path: :string
      ],
      required: [:module]
    }
  end

  @impl Igniter.Mix.Task
  def igniter(igniter) do
    module_name = igniter.args.options[:module]
    baml_path = igniter.args.options[:path] || "baml_src"

    unless module_name do
      Mix.shell().error("Error: --module is required")
      Mix.shell().info(@moduledoc)
      System.halt(1)
    end

    client_module = Module.concat([module_name])

    igniter
    |> create_client_module(client_module, baml_path)
    |> create_baml_directory(baml_path)
    |> create_example_baml_files(baml_path)
    |> add_success_notice(client_module, baml_path)
  end

  defp create_client_module(igniter, module_name, baml_path) do
    module_contents = ~s"""
    @moduledoc \"\"\"
    BAML client for #{inspect(module_name)}.

    Generated by ash_baml. This module provides the interface to BAML functions
    defined in #{baml_path}/.

    To regenerate types after modifying BAML schemas:

        mix ash_baml.gen.types #{inspect(module_name)}
    \"\"\"

    use BamlElixir.Client,
      baml_src: "#{baml_path}"

    def __baml_src_path__ do
      Path.join(File.cwd!(), "#{baml_path}")
    end
    """

    Igniter.Project.Module.create_module(igniter, module_name, module_contents)
  end

  defp create_baml_directory(igniter, baml_path) do
    Igniter.create_new_file(igniter, "#{baml_path}/.gitkeep", "", on_exists: :skip)
  end

  defp create_example_baml_files(igniter, baml_path) do
    igniter
    |> create_clients_baml(baml_path)
    |> create_example_function_baml(baml_path)
  end

  defp create_clients_baml(igniter, baml_path) do
    clients_content = """
    // Configure your LLM clients here
    // See: https://docs.boundaryml.com/docs/snippets/clients

    client<llm> GPT4 {
      provider openai
      options {
        model gpt-4
        api_key env.OPENAI_API_KEY
      }
    }

    client<llm> GPT4Turbo {
      provider openai
      options {
        model gpt-4-turbo-preview
        api_key env.OPENAI_API_KEY
      }
    }

    client<llm> Claude {
      provider anthropic
      options {
        model claude-3-5-sonnet-20241022
        api_key env.ANTHROPIC_API_KEY
      }
    }
    """

    Igniter.create_new_file(igniter, "#{baml_path}/clients.baml", clients_content,
      on_exists: :skip
    )
  end

  defp create_example_function_baml(igniter, baml_path) do
    example_content = """
    // Example BAML function
    // Delete this file and create your own functions

    function ExtractUser(text: string) -> User {
      client GPT4Turbo
      prompt #"
        Extract user information from the following text:

        {{ text }}

        {{ ctx.output_format }}
      "#
    }

    class User {
      name string
      email string | null
      age int | null
    }
    """

    Igniter.create_new_file(igniter, "#{baml_path}/example.baml", example_content,
      on_exists: :skip
    )
  end

  defp add_success_notice(igniter, module_name, baml_path) do
    notice = """

    BAML client installed successfully!

    Generated:
      - Client module: #{inspect(module_name)}
      - BAML directory: #{baml_path}/
      - Example files: clients.baml, example.baml

    Next steps:
      1. Configure your LLM API keys in #{baml_path}/clients.baml
      2. Define your BAML functions in #{baml_path}/
      3. Generate types: mix ash_baml.gen.types #{inspect(module_name)}
      4. Use the generated types in your Ash resources
    """

    Igniter.add_notice(igniter, notice)
  end

  @impl Igniter.Mix.Task
  def supports_umbrella?, do: false

  @impl Igniter.Mix.Task
  def installer?, do: true
end
