defmodule Mix.Tasks.AshBaml.Install do
  use Igniter.Mix.Task

  alias Igniter.Code.Common
  alias Igniter.Code.List
  alias Igniter.Project.Config

  @shortdoc "Generates a BAML client module and example BAML files"

  @moduledoc """
  #{@shortdoc}

  ## Examples

  ```bash
  # Generate config-driven client setup (recommended)
  mix ash_baml.install --client support --path baml_src/support

  # Generate multiple clients
  mix ash_baml.install --client support --path baml_src/support
  mix ash_baml.install --client content --path baml_src/content

  # Legacy: Generate standalone client module file
  mix ash_baml.install --module MyApp.BamlClient --path baml_src
  ```

  ## Options

  * `--client` - Client identifier (e.g., :support). Recommended approach.
  * `--module` - Module name for legacy standalone client file
  * `--path` - Path to baml_src directory. Defaults to "baml_src"

  Note: Specify either `--client` or `--module`, not both.
  """

  def info(_argv, _composing_task) do
    %Igniter.Mix.Task.Info{
      schema: [
        client: :string,
        module: :string,
        path: :string
      ],
      required: []
    }
  end

  @impl Igniter.Mix.Task
  def igniter(igniter) do
    client_id = igniter.args.options[:client]
    module_name = igniter.args.options[:module]
    baml_path = igniter.args.options[:path] || "baml_src"

    cond do
      client_id && module_name ->
        Igniter.add_warning(igniter, """
        Specify either --client or --module, not both.

        For config-driven clients (recommended):
          mix ash_baml.install --client support --path baml_src/support

        For legacy standalone module:
          mix ash_baml.install --module MyApp.BamlClient --path baml_src
        """)

      client_id ->
        validated_client_id = validate_client_identifier(client_id)
        install_config_driven_client(igniter, validated_client_id, baml_path)

      module_name ->
        install_legacy_client(igniter, Module.concat([module_name]), baml_path)

      true ->
        Igniter.add_warning(igniter, """
        Must specify either --client or --module.

        For config-driven clients (recommended):
          mix ash_baml.install --client support --path baml_src/support

        For legacy standalone module:
          mix ash_baml.install --module MyApp.BamlClient --path baml_src
        """)
    end
  end

  defp validate_client_identifier(client_id) when is_binary(client_id) do
    if client_id =~ ~r/^[a-z][a-z0-9_]*$/ do
      String.to_atom(client_id)
    else
      raise """
      Invalid client identifier: #{inspect(client_id)}

      Client identifiers must:
      - Start with a lowercase letter
      - Contain only lowercase letters, numbers, and underscores

      Examples: support, content, main_client
      """
    end
  end

  defp install_config_driven_client(igniter, client_id, baml_path) do
    app_name = Igniter.Project.Application.app_name(igniter)
    module_base = app_name |> Atom.to_string() |> Macro.camelize()

    module_name =
      Module.concat([module_base, "BamlClients", Macro.camelize(to_string(client_id))])

    igniter
    |> add_client_to_config(client_id, module_name, baml_path)
    |> create_baml_directory(baml_path)
    |> create_example_baml_files(baml_path)
    |> add_config_driven_notice(client_id, module_name, baml_path)
  end

  defp install_legacy_client(igniter, module_name, baml_path) do
    igniter
    |> create_legacy_client_module(module_name, baml_path)
    |> create_baml_directory(baml_path)
    |> create_example_baml_files(baml_path)
    |> add_legacy_notice(module_name, baml_path)
  end

  defp add_client_to_config(igniter, client_id, module_name, baml_path) do
    Config.configure(
      igniter,
      "config.exs",
      :ash_baml,
      [:clients],
      [{client_id, {module_name, [baml_src: baml_path]}}],
      updater: fn zipper ->
        case Common.move_to_cursor_match_in_scope(
               zipper,
               "{:clients, __cursor__()}"
             ) do
          {:ok, zipper} ->
            List.append_to_list(
              zipper,
              {client_id, {module_name, [baml_src: baml_path]}}
            )

          :error ->
            IO.warn("""
            Failed to add client configuration to config.exs automatically.

            Please manually add the following to config/config.exs:

                config :ash_baml,
                  clients: [
                    #{client_id}: {#{inspect(module_name)}, baml_src: "#{baml_path}"}
                  ]
            """)

            {:ok, zipper}
        end
      end
    )
  end

  defp create_legacy_client_module(igniter, module_name, baml_path) do
    module_contents = ~s"""
    @moduledoc \"\"\"
    BAML client for #{inspect(module_name)}.

    Generated by ash_baml. This module provides the interface to BAML functions
    defined in #{baml_path}/.

    To regenerate types after modifying BAML schemas:

        mix ash_baml.gen.types #{inspect(module_name)}
    \"\"\"

    use BamlElixir.Client, path: "#{baml_path}"
    """

    Igniter.Project.Module.create_module(igniter, module_name, module_contents)
  end

  defp create_baml_directory(igniter, baml_path) do
    Igniter.create_new_file(igniter, "#{baml_path}/.gitkeep", "", on_exists: :skip)
  end

  defp create_example_baml_files(igniter, baml_path) do
    igniter
    |> create_clients_baml(baml_path)
    |> create_example_function_baml(baml_path)
  end

  defp create_clients_baml(igniter, baml_path) do
    clients_content = """
    // Configure your LLM clients here
    // See: https://docs.boundaryml.com/docs/snippets/clients

    client<llm> GPT5 {
      provider openai
      options {
        model gpt-5
        api_key env.OPENAI_API_KEY
      }
    }

    client<llm> GPT5Mini {
      provider openai
      options {
        model gpt-5-mini
        api_key env.OPENAI_API_KEY
      }
    }

    client<llm> Claude {
      provider anthropic
      options {
        model claude-4-5-sonnet
        api_key env.ANTHROPIC_API_KEY
      }
    }
    """

    Igniter.create_new_file(igniter, "#{baml_path}/clients.baml", clients_content,
      on_exists: :skip
    )
  end

  defp create_example_function_baml(igniter, baml_path) do
    example_content = """
    // Example BAML function
    // Delete this file and create your own functions

    function ExtractUser(text: string) -> User {
      client GPT5Mini
      prompt #"
        Extract user information from the following text:

        {{ text }}

        {{ ctx.output_format }}
      "#
    }

    class User {
      name string
      email string | null
      age int | null
    }
    """

    Igniter.create_new_file(igniter, "#{baml_path}/example.baml", example_content,
      on_exists: :skip
    )
  end

  defp add_config_driven_notice(igniter, client_id, module_name, baml_path) do
    notice = """

    Config-driven BAML client installed successfully!

    Configuration added to config/config.exs:
      Client ID: :#{client_id}
      Module: #{inspect(module_name)}
      BAML source: #{baml_path}/

    Generated:
      - BAML directory: #{baml_path}/
      - Example files: clients.baml, example.baml

    The client module will be auto-generated at compile time.
    No manual client file needed!

    Next steps:
      1. Configure your LLM API keys in #{baml_path}/clients.baml
      2. Define your BAML functions in #{baml_path}/
      3. Generate types: mix ash_baml.gen.types #{inspect(module_name)}
      4. Use in your Ash resources:

          baml do
            client :#{client_id}
            import_functions [:YourFunction]
          end
    """

    Igniter.add_notice(igniter, notice)
  end

  defp add_legacy_notice(igniter, module_name, baml_path) do
    notice = """

    Legacy BAML client installed successfully!

    Generated:
      - Client module: #{inspect(module_name)}
      - BAML directory: #{baml_path}/
      - Example files: clients.baml, example.baml

    Next steps:
      1. Configure your LLM API keys in #{baml_path}/clients.baml
      2. Define your BAML functions in #{baml_path}/
      3. Generate types: mix ash_baml.gen.types #{inspect(module_name)}
      4. Use in your Ash resources:

          baml do
            client_module #{inspect(module_name)}
            import_functions [:YourFunction]
          end

    Consider migrating to config-driven clients for less boilerplate.
    """

    Igniter.add_notice(igniter, notice)
  end

  @impl Igniter.Mix.Task
  def supports_umbrella?, do: false

  @impl Igniter.Mix.Task
  def installer?, do: true
end
