defmodule AshBaml.ClientBuilder do
  @moduledoc false

  @type client_identifier :: atom()
  @type client_config :: [{client_identifier(), {module(), keyword()}}]

  @spec ensure_configured_client_module(client_identifier(), client_config() | nil) ::
          {:ok, module()} | {:error, String.t()}
  def ensure_configured_client_module(identifier, clients \\ nil) do
    clients = clients || Application.get_env(:ash_baml, :clients, [])

    case Keyword.get(clients, identifier) do
      nil ->
        {:error, client_not_configured_error(identifier, clients)}

      {module_name, opts} ->
        baml_src = Keyword.get(opts, :baml_src)

        case {Code.ensure_loaded?(module_name), baml_src} do
          {true, nil} ->
            {:ok, module_name}

          {_, path} when is_binary(path) or is_list(path) ->
            with :ok <- ensure_client_module(module_name, path) do
              {:ok, module_name}
            end

          {true, _} ->
            {:ok, module_name}

          _ ->
            {:error,
             """
             BAML client #{inspect(identifier)} is configured to use #{inspect(module_name)}
             but no :baml_src was provided, so the module cannot be auto-generated.
             Provide :baml_src or predefine #{inspect(module_name)} manually.
             """}
        end
    end
  end

  @spec ensure_client_module(module(), String.t()) :: :ok | {:error, String.t()}
  def ensure_client_module(module_name, baml_src) do
    creation_key = {:ash_baml_client_creation, module_name}

    cond do
      module_already_loaded_with_same_source?(module_name, baml_src) ->
        :ok

      Code.ensure_loaded?(module_name) ->
        warn_module_already_loaded(module_name)
        :ok

      Module.open?(module_name) ->
        :ok

      already_creating?(creation_key) ->
        :ok

      true ->
        create_baml_client_module(module_name, baml_src, creation_key)
    end
  end

  defp module_already_loaded_with_same_source?(module_name, baml_src) do
    Code.ensure_loaded?(module_name) and
      function_exported?(module_name, :__baml_src_path__, 0) and
      module_name.__baml_src_path__() == Path.expand(baml_src, File.cwd!())
  end

  defp warn_module_already_loaded(module_name) do
    IO.warn("""
    BAML client module #{inspect(module_name)} is already loaded.
    Config changes detected but module cannot be reloaded during compilation.

    To apply changes:
    1. Restart your application/IEx session
    2. Or run: mix compile --force
    """)
  end

  defp create_baml_client_module(module_name, baml_src, creation_key) do
    mark_creating(creation_key)

    try do
      {:module, _module, _binary, _result} =
        Module.create(
          module_name,
          quote location: :keep do
            @moduledoc """
            Auto-generated BAML client module.

            Generated by AshBaml from application config.
            Do not modify this module manually.

            BAML source: #{unquote(baml_src)}
            """

            use BamlElixir.Client, path: unquote(baml_src)

            def __baml_src_path__ do
              Path.expand(unquote(baml_src), File.cwd!())
            end
          end,
          Macro.Env.location(__ENV__)
        )

      :ok
    rescue
      e in CompileError ->
        handle_compile_error(e, module_name)

      e ->
        {:error, "Failed to create BAML client module #{inspect(module_name)}: #{inspect(e)}"}
    after
      unmark_creating(creation_key)
    end
  end

  defp handle_compile_error(error, module_name) do
    if (String.contains?(error.description, "cannot compile module") or
          String.contains?(error.description, "cannot define module")) and
         String.contains?(error.description, "currently being defined") do
      :ok
    else
      {:error, "Failed to create BAML client module #{inspect(module_name)}: #{inspect(error)}"}
    end
  end

  defp already_creating?(key) do
    :persistent_term.get(key, false)
  end

  defp mark_creating(key) do
    :persistent_term.put(key, true)
  end

  defp unmark_creating(key) do
    :persistent_term.erase(key)
  end

  defp client_not_configured_error(identifier, available_clients) do
    available =
      case available_clients do
        [] -> "No clients configured"
        clients -> "Available: #{inspect(Keyword.keys(clients))}"
      end

    """
    BAML client :#{identifier} not found in application config.

    #{available}

    Add to config/config.exs:

        config :ash_baml,
          clients: [
            #{identifier}: {MyApp.BamlClient, baml_src: "baml_src"}
          ]
    """
  end
end
