defmodule AshBaml.Helpers do
  @moduledoc """
  Helper macros for using BAML functions in Ash actions.
  """

  @doc """
  Calls a BAML function from an Ash action.

  This macro expands to an action implementation that delegates to the
  BAML function module generated by `BamlElixir.Client`.

  This macro is automatically available when using the `AshBaml.Resource` extension.

  ## Example

      actions do
        action :chat, MyApp.BamlClient.Reply do
          argument :message, :string
          run call_baml(:ChatAgent)
        end
      end

  ## How It Works

  1. Gets the `client_module` from the resource's `baml` configuration
  2. Constructs the function module: `ClientModule.FunctionName`
  3. Calls `FunctionModule.call(arguments)`
  4. Returns `{:ok, result}` or `{:error, reason}`

  ## Arguments

  - `function_name` - Atom matching a BAML function name

  ## Options (via `call_baml/2`)

  - `telemetry: false` - Disable telemetry for this specific call
  - `telemetry: keyword()` - Override telemetry configuration
  """
  defmacro call_baml(function_name) when is_atom(function_name) do
    quote do
      {AshBaml.Actions.CallBamlFunction, [function: unquote(function_name)]}
    end
  end

  @doc """
  Calls a BAML function with options.

  Accepts the same options as `call_baml/1`, plus additional options
  for controlling execution behavior.

  ## Options

  - `telemetry: false` - Disable telemetry for this specific call
  - `telemetry: keyword()` - Override telemetry configuration (e.g., `sample_rate: 0.1`)

  ## Examples

      # Disable telemetry for this call
      run call_baml(:InternalFunction, telemetry: false)

      # Override sample rate for expensive function
      run call_baml(:ExpensiveFunction, telemetry: [sample_rate: 0.1])
  """
  defmacro call_baml(function_name, opts) when is_atom(function_name) do
    quote do
      {AshBaml.Actions.CallBamlFunction,
       Keyword.merge([function: unquote(function_name)], unquote(opts))}
    end
  end

  @doc """
  Macro for calling BAML functions with streaming.

  Returns a Stream that emits chunks as they arrive from the LLM.

  ## Example

      action :chat_stream, AshBaml.Type.Stream do
        argument :message, :string
        run call_baml_stream(:ChatAgent)
      end
  """
  defmacro call_baml_stream(function_name) when is_atom(function_name) do
    quote do
      {AshBaml.Actions.CallBamlStream, [function: unquote(function_name)]}
    end
  end
end
