defmodule AshBaml.Helpers do
  @moduledoc """
  Helper macros for using BAML functions in Ash actions.
  """

  @doc """
  Calls a BAML function from an Ash action.

  This macro expands to an action implementation that delegates to the
  BAML function module generated by `BamlElixir.Client`.

  ## Example

      import AshBaml.Helpers

      actions do
        action :chat, MyApp.BamlClient.Reply do
          argument :message, :string
          run call_baml(:ChatAgent)
        end
      end

  ## How It Works

  1. Gets the `client_module` from the resource's `baml` configuration
  2. Constructs the function module: `ClientModule.FunctionName`
  3. Calls `FunctionModule.call(arguments)`
  4. Returns `{:ok, result}` or `{:error, reason}`

  ## Arguments

  - `function_name` - Atom matching a BAML function name

  ## Options

  None for Phase 1. Future phases will support:
  - `client: :atom` - Override client
  - `stream: boolean` - Enable streaming
  """
  defmacro call_baml(function_name) when is_atom(function_name) do
    quote do
      {AshBaml.Actions.CallBamlFunction, [function: unquote(function_name)]}
    end
  end
end
