/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "test_functions.baml": "client<llm> TestClient {\n  provider openai\n  options {\n    model gpt-4o-mini\n    api_key env.OPENAI_API_KEY\n  }\n}\n\nclass Reply {\n  content string\n  confidence float\n}\n\nfunction TestFunction(message: string) -> Reply {\n  client TestClient\n  prompt #\"\n    You are a test assistant.\n    User: {{ message }}\n    {{ ctx.output_format }}\n  \"#\n}\n\nclass MultiArgResponse {\n  greeting string\n  description string\n  age_category string\n}\n\nfunction MultiArgFunction(name: string, age: int, topic: string) -> MultiArgResponse {\n  client TestClient\n  prompt #\"\n    Create a personalized greeting for {{ name }} who is {{ age }} years old.\n    Then provide a brief description about {{ topic }}.\n    Finally, categorize the age as: child (0-12), teen (13-19), adult (20-64), or senior (65+).\n    {{ ctx.output_format }}\n  \"#\n}\n\nclass ProfileResponse {\n  bio string\n  interests string[]\n  location string?\n}\n\nfunction OptionalArgsFunction(name: string, age: int, location: string?) -> ProfileResponse {\n  client TestClient\n  prompt #\"\n    Create a profile for {{ name }} who is {{ age }} years old.\n    {% if location %}\n    They are located in {{ location }}.\n    {% else %}\n    Location is not specified.\n    {% endif %}\n    Provide a brief bio, a list of potential interests, and include the location if provided.\n    {{ ctx.output_format }}\n  \"#\n}\n",
  "tool_functions.baml": "client<llm> TestToolClient {\n  provider openai\n  options {\n    model gpt-4o-mini\n    api_key env.OPENAI_API_KEY\n  }\n}\n\nclass WeatherTool {\n  city string @description(\"City name for weather lookup\")\n  units string @description(\"Temperature units: celsius or fahrenheit\")\n}\n\nclass CalculatorTool {\n  operation \"add\" | \"subtract\" | \"multiply\" | \"divide\"\n  numbers float[] @description(\"Numbers to perform operation on\")\n}\n\nfunction SelectTool(message: string) -> WeatherTool | CalculatorTool {\n  client TestToolClient\n  prompt #\"\n    Based on the user's message, determine which tool to call.\n    Extract the necessary parameters for the selected tool.\n\n    {{ ctx.output_format }}\n\n    User message: {{ message }}\n  \"#\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}