/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CalculatorTool,  MultiArgResponse,  ProfileResponse,  Reply,  WeatherTool } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CalculatorTool {
      operation?: "add" | "subtract" | "multiply" | "divide" | null
      numbers: number[]
    }
    export interface MultiArgResponse {
      greeting?: string | null
      description?: string | null
      age_category?: string | null
    }
    export interface ProfileResponse {
      bio?: string | null
      interests: string[]
      location?: string | null
    }
    export interface Reply {
      content?: string | null
      confidence?: number | null
    }
    export interface WeatherTool {
      city?: string | null
      units?: string | null
    }
}